### ISSUE TITLE
Individual and Team Photograph

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/website#1]
Cassini had mentioned that next week is when we would be taking photographs.

**Comment by jjdoyle2010** [comment]
@linamoon

**Comment by linamoon** [comment]
@geoffreyvillalba The mugshot photos and the photos from class are on the google drive for post-processing. The Selected folders have the nicer ones.

**Comment by linamoon** [comment]
Need to retake photo for @kelseeswenn since her background isn't same as the others, take photo of @shruthiravi15 , confirm with @cassininazir that we got everyone. Should we also include @lanceking as well if possible?

@greyhound77 would you mind bringing your lens again for next week? 

@davidowproject/owners don't forget group photo for next week!

**Comment by greyhound77** [comment]
For sure!

**Comment by cassininazir** [comment]
Yes on including Lance, he will be in class next week.

Attachign a roster of everyone for you to compare.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by jjdoyle2010** [comment]
@linamoon If possible, let's also get group photos of each of the individual groups as well. Since there are so many people it may be necessary to have team bios separated into their own group pages.

**Comment by judyn** [comment]
^I like this idea!

**Comment by linamoon** [comment]
Yes, agreed!

**Comment by linamoon** [comment]
Noticed while editing photos - we forgot to get a headshot of Mithun. @shruthiravi15 , do you have his contact info so that I could perhaps schedule him for a shot?

**Comment by linamoon** [comment]
@summersaylor Already emailed you, just documenting that all photos should be on the Google Drive.

**Comment by summersaylor** [comment]
Hey Lina,

Got the email and found the pics, thank you! Just cleaning up the final
presentation now.

**Comment by linamoon** [comment]
Also for the headshots - I know there's a folder called Cropped that has them cropped to a square, but I was thinking the portrait crops might be better. Just FYI.

**Comment by linamoon** [comment]
@shruthiravi15 Contacted Mithun and Morgan for the shots, we're good.

**Comment by shruthiravi15** [comment]
Ok sorry for this late reply. Let me know if you need anythingn else

**Comment by jjdoyle2010** [comment]
@linamoon Did we ever get the group photos uploaded onto the drive?

**Comment by judyn** [comment]
They're in there under Yearbook Shots

**Comment by jjdoyle2010** [comment]
Thanks.
