### ISSUE TITLE
Team Member Bios

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/website#10]
If you would like to make any last minute changes to your bio Let me know. @davidowproject/owners 

https://drive.google.com/drive/u/0/folders/0B6Vhc_NXSgDZfjZzZlR2VUpiYmMtTEUteWNEdE93WlpkTTEzMnVuaHdGajYzNURpWnlPd0U

**Comment by jjdoyle2010** [comment]
@davidowproject/owners Some people were confused about what to put in terms of websites. You can put any website that would be a good way for people that might want to contact you(team members, people that might want to hire you, ect). Such as Twitter, your own website, linkedin, ect.(pref not facebook or instagram)

**Comment by cassininazir** [comment]
Thanks, James. Completely agreed here. The goal is to benefit you for your portfolio and resume: you�ll have a website that you may refer to in the long-run and a project that you may add to your portfolio. Probably don�t want your future employer going to your Facebook or Instagram pages.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by linamoon** [comment]
@jjdoyle2010 - was checking the bios against the class roster. We're missing:
- You! James Doyle
- Dylan Orgeron
- Clarice Yeow

Correct me if I'm wrong, but I don't think an Ashley Stone is in our class?

**Comment by summersaylor** [comment]
Pretty sure Ashley Stone is also known as Morgan, from the Research team.
Duncan and I have her personal email if you need.

**Comment by linamoon** [comment]
Ah darn, we didn't get her pic either. I'll email her.

**Comment by linamoon** [comment]
@cassininazir got your bio on the Google Drive; @lanceking would like yours as well, as well as a link to personal site/linkedin if you like.

**Comment by linamoon** [comment]
Actually @lanceking stole it from your capstone website - if you'd like to make any changes, the doc is at

https://docs.google.com/document/d/1pb5xJzHyMukM04b4ukPLxKNEmoGb8ZbpuXCjGf-V_X8/edit?usp=sharing

**Comment by summersaylor** [comment]
No more bios, just pop-out links.
