### ISSUE TITLE
Website Bad Information/ Typos

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/website#11]
Hey all. I'll be going through and adding what content we have completed to the website during the week. If you have a chance later in the week to go through and make sure I didn't make any mistakes(wrong names to photos, wrong links, ect) it would be helpful for me.

I've just started, currently working on the Team page.

@davidowproject/owners 

Also if you have any suggestions those are nice too.

www.davidow.atec.io

**Comment by jjdoyle2010** [comment]
Created teams own pages. Will link to them with team photos on Our Team Page. Lance and Cassini will be on that main page.

www.davidow.atec.io/ui
www.davidow.atec.io/research
www.davidow.atec.io/code

**Comment by summersaylor** [comment]
Typos have been fixed and no more individual pages - one long page now.
