### ISSUE TITLE
Process Info-graphic?

### ISSUE THREAD

**Issue by jjdoyle2010** [davidowproject/website#9]
We need to figure out how we are going to present our process on the website. Any ideas would be helpful.

**Comment by lanceking** [comment]
I vote for interpretive dance. This will describe the process perfectly.

YouTube it if you don't know what it is, you'll laugh.

**Comment by summersaylor** [comment]
@kiraamin is going to pull together 4 sketches of this by next class. She will be contacting the code and research teams to get an idea of project milestones.

**Comment by summersaylor** [comment]
Moved away from an infographic in favor of a responsive text and image layout.
